import react, {useContext} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import css from '../styles/Home.module.scss'
import { LoginContext } from '../context/LoginContext'


export default function Home() {

  

  return (
    <div className={css.global_container}>
      <Head>
        <title>Fake Eshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>Hello </h1>

    </div>
  )
}
